version: '3.8'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10020:8080"
    depends_on:
      - postgresdb

  nginx:
    image: nginx:latest
    ports:
      - "20020:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - goapp

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: practice
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
